CREATE DATABASE CASESTUDY1

USE CASESTUDY1

-- Display the number of states present in the Location Table.
SELECT COUNT(DISTINCT(STATE)) AS NO_OF_STATES
FROM LOCATION

-- How many products are of regular type?
SELECT COUNT(*) AS REG_TYPE
FROM PRODUCT
WHERE TYPE='REGULAR'

-- How much spending has been done on marketing of product ID 1?
SELECT SUM(MARKETING) AS SPENDS
FROM FACT
WHERE PRODUCTID=1

-- What is the minimum sales of a product?
SELECT MIN(SALES) AS MIN_SALE
FROM FACT

-- Display the max Cost of Good Sold (COGS).
SELECT MAX(COGS) AS MAX_COFS
FROM FACT

-- What is the average sales in area code 719?
SELECT AVG(SALES) AS AVG_SALE
FROM FACT
WHERE AREA_CODE=719

-- Find out the total profit generated by Colorado state.
SELECT SUM(PROFIT) AS TOT_PROFIT
FROM FACT F
JOIN LOCATION L
ON F.AREA_CODE=L.AREA_CODE
WHERE STATE='COLORADO'

-- Display the average inventory for each product ID.
SELECT PRODUCTID,AVG(INVENTORY) AS AVG_INV
FROM FACT
GROUP BY PRODUCTID

-- Display the average budget of the Product where the average budget margin should be greater than 100.
SELECT PRODUCTID,AVG(BUDGET_MARGIN) AS AVG_BUD
FROM FACT
GROUP BY PRODUCTID
HAVING AVG(BUDGET_MARGIN)>100

-- What is the total sales done on date 2010-01-01?
SELECT SUM(SALES) AS TOT_SALE
FROM FACT
WHERE DATE='2010-01-01'

-- Display the average total expense of each product ID on an individual date.
SELECT PRODUCTID,DATE,AVG(TOTAL_EXPENSES) AS AVG_TOT_SALE
FROM FACT
GROUP BY PRODUCTID,DATE

-- Find the state wise profit and sales.
SELECT L.STATE,SUM(F.PROFIT) AS PROFIT,SUM(F.SALES) AS SALES
FROM FACT F
JOIN LOCATION L
ON F.AREA_CODE=L.AREA_CODE
GROUP BY STATE
